CREATE SEQUENCE REVIEW_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE NOTICE_SEQ START WITH 1 INCREMENT BY 1;

SELECT * FROM MEMBER;
SELECT * FROM MEMBER_MEMBER_ROLE_LIST order by member_email asc;
SELECT * FROM MOVIE;
SELECT * FROM REVIEW;

SELECT * FROM NOTICE;



SELECT * FROM ALL_CONSTRAINTS
WHERE TABLE_NAME = 'MEMBER_MEMBER_ROLE_LIST';
